services:
  backoffice-api:
    image: backoffice-api
    container_name: backoffice-api
    build:
      context: .
      dockerfile: backoffice-api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - midori-network

  postgres-db:
    image: postgres:latest
    container_name: postgres.db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: midori-backoffice
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - midori-network

networks:
  midori-network:
    driver: bridge


volumes:
  postgres_data:
    driver: local